Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
APP:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/log
  LogFileName: app
  LogFileEXT: .log
  LogMaxSize: 10  #默认10M切割
  MaxBackups: 30
  MaxAge: 7
  Compress: true
  LogLevel: "debug"
Datebase:
  DBType: mysql
  Username: root
  Password: Dyg@12345
  Host: 192.168.2.103:30336
  DBName: jzblog
  TablePrefix: blog_
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30